# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/cyoh001/lab-07-factory-pattern-fun_stuff_lab7

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/cyoh001/lab-07-factory-pattern-fun_stuff_lab7

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/cyoh001/lab-07-factory-pattern-fun_stuff_lab7/CMakeFiles /home/csmajs/cyoh001/lab-07-factory-pattern-fun_stuff_lab7/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/cyoh001/lab-07-factory-pattern-fun_stuff_lab7/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named calculator

# Build rule for target.
calculator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calculator
.PHONY : calculator

# fast build rule for target.
calculator/fast:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/build
.PHONY : calculator/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

Add.o: Add.cpp.o

.PHONY : Add.o

# target to build an object file
Add.cpp.o:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Add.cpp.o
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Add.cpp.o
.PHONY : Add.cpp.o

Add.i: Add.cpp.i

.PHONY : Add.i

# target to preprocess a source file
Add.cpp.i:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Add.cpp.i
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Add.cpp.i
.PHONY : Add.cpp.i

Add.s: Add.cpp.s

.PHONY : Add.s

# target to generate assembly for a file
Add.cpp.s:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Add.cpp.s
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Add.cpp.s
.PHONY : Add.cpp.s

Div.o: Div.cpp.o

.PHONY : Div.o

# target to build an object file
Div.cpp.o:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Div.cpp.o
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Div.cpp.o
.PHONY : Div.cpp.o

Div.i: Div.cpp.i

.PHONY : Div.i

# target to preprocess a source file
Div.cpp.i:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Div.cpp.i
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Div.cpp.i
.PHONY : Div.cpp.i

Div.s: Div.cpp.s

.PHONY : Div.s

# target to generate assembly for a file
Div.cpp.s:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Div.cpp.s
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Div.cpp.s
.PHONY : Div.cpp.s

Factory.o: Factory.cpp.o

.PHONY : Factory.o

# target to build an object file
Factory.cpp.o:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Factory.cpp.o
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Factory.cpp.o
.PHONY : Factory.cpp.o

Factory.i: Factory.cpp.i

.PHONY : Factory.i

# target to preprocess a source file
Factory.cpp.i:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Factory.cpp.i
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Factory.cpp.i
.PHONY : Factory.cpp.i

Factory.s: Factory.cpp.s

.PHONY : Factory.s

# target to generate assembly for a file
Factory.cpp.s:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Factory.cpp.s
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Factory.cpp.s
.PHONY : Factory.cpp.s

Mult.o: Mult.cpp.o

.PHONY : Mult.o

# target to build an object file
Mult.cpp.o:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Mult.cpp.o
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Mult.cpp.o
.PHONY : Mult.cpp.o

Mult.i: Mult.cpp.i

.PHONY : Mult.i

# target to preprocess a source file
Mult.cpp.i:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Mult.cpp.i
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Mult.cpp.i
.PHONY : Mult.cpp.i

Mult.s: Mult.cpp.s

.PHONY : Mult.s

# target to generate assembly for a file
Mult.cpp.s:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Mult.cpp.s
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Mult.cpp.s
.PHONY : Mult.cpp.s

Sub.o: Sub.cpp.o

.PHONY : Sub.o

# target to build an object file
Sub.cpp.o:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Sub.cpp.o
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sub.cpp.o
.PHONY : Sub.cpp.o

Sub.i: Sub.cpp.i

.PHONY : Sub.i

# target to preprocess a source file
Sub.cpp.i:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Sub.cpp.i
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sub.cpp.i
.PHONY : Sub.cpp.i

Sub.s: Sub.cpp.s

.PHONY : Sub.s

# target to generate assembly for a file
Sub.cpp.s:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Sub.cpp.s
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sub.cpp.s
.PHONY : Sub.cpp.s

base.o: base.cpp.o

.PHONY : base.o

# target to build an object file
base.cpp.o:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/base.cpp.o
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/base.cpp.o
.PHONY : base.cpp.o

base.i: base.cpp.i

.PHONY : base.i

# target to preprocess a source file
base.cpp.i:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/base.cpp.i
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/base.cpp.i
.PHONY : base.cpp.i

base.s: base.cpp.s

.PHONY : base.s

# target to generate assembly for a file
base.cpp.s:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/base.cpp.s
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/base.cpp.s
.PHONY : base.cpp.s

calculator.o: calculator.cpp.o

.PHONY : calculator.o

# target to build an object file
calculator.cpp.o:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/calculator.cpp.o
.PHONY : calculator.cpp.o

calculator.i: calculator.cpp.i

.PHONY : calculator.i

# target to preprocess a source file
calculator.cpp.i:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/calculator.cpp.i
.PHONY : calculator.cpp.i

calculator.s: calculator.cpp.s

.PHONY : calculator.s

# target to generate assembly for a file
calculator.cpp.s:
	$(MAKE) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/calculator.cpp.s
.PHONY : calculator.cpp.s

op_test.o: op_test.cpp.o

.PHONY : op_test.o

# target to build an object file
op_test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/op_test.cpp.o
.PHONY : op_test.cpp.o

op_test.i: op_test.cpp.i

.PHONY : op_test.i

# target to preprocess a source file
op_test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/op_test.cpp.i
.PHONY : op_test.cpp.i

op_test.s: op_test.cpp.s

.PHONY : op_test.s

# target to generate assembly for a file
op_test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/op_test.cpp.s
.PHONY : op_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... calculator"
	@echo "... test"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... Add.o"
	@echo "... Add.i"
	@echo "... Add.s"
	@echo "... Div.o"
	@echo "... Div.i"
	@echo "... Div.s"
	@echo "... Factory.o"
	@echo "... Factory.i"
	@echo "... Factory.s"
	@echo "... Mult.o"
	@echo "... Mult.i"
	@echo "... Mult.s"
	@echo "... Sub.o"
	@echo "... Sub.i"
	@echo "... Sub.s"
	@echo "... base.o"
	@echo "... base.i"
	@echo "... base.s"
	@echo "... calculator.o"
	@echo "... calculator.i"
	@echo "... calculator.s"
	@echo "... op_test.o"
	@echo "... op_test.i"
	@echo "... op_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

